### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by ghost** [Lemon4ik666/Lethal-Company-Anti-Kick-Mod#1]
Can you please make realese, i had to download compiler myself, and compile it.

**Comment by Lemon4ik666** [comment]
> Can you please make realese, i had to download compiler myself, and compile it.

Okay

**Comment by Lemon4ik666** [comment]
> Can you please make realese, i had to download compiler myself, and compile it.

I released the release, good luck :)

**Comment by ghost** [comment]
Thank you.
